### ISSUE TITLE
SystemController

### ISSUE THREAD

**Issue by BorodinDmitriy** [ConteDevel/4share#12]
Есть пара методов со схожим написанием. Возможно, имеет смысл объединить их в один.
![image](https://user-images.githubusercontent.com/22422156/35199248-b928380a-ff0c-11e7-9157-db03c46e8444.png)

**Comment by puchninanastya** [comment]
Объединение mute/unmute команд c командой изменения уровня громкости сделает код более запутанным, так как, во-первых, является неочевидным, например, что команда set 100% при включенном mute, не устанавливает unmute значение, и, во-вторых, с помощью сигналов придется передавать параметры, не касающиеся напрямую текущей команды.

**Comment by BorodinDmitriy** [comment]
Тогда можно оставить, как есть.
